# version: 2.1
# executors:
#   my-custom-executor:
#     docker:
#       - image: cimg/base:stable
#         auth:
#           # ensure you have first added these secrets
#           # visit app.circleci.com/settings/project/github/LindaLi0609/api-cypress/environment-variables
#           username: $DOCKER_HUB_USER
#           password: $DOCKER_HUB_PASSWORD
# jobs:
#   api-test:

#     executor: my-custom-executor
#     steps:
#       - checkout
#       - run: $(npm bin)/cypress run
#           # echo Hello, World!
#       - store_test_results:
#           path: 'cypress\test_results'
#       - store_artifacts:
#           path: ~/repo/testing-apis-with-cypress

# workflows:
#   my-custom-workflow:
#     jobs:
#       - api-test
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run
      - store_artifacts:
          path: ~/repo/testing-apis-with-cypress
      - store_test_results:
          path: 'cypress\test_results'
